### ISSUE TITLE
I see app is not reading OTP

### ISSUE THREAD

**Issue by ghost** [sidpagariya/cowin-notifier#3]
Hi,
 just want to knw how this work? do we need to update mobile number in ifttt . how ifttt workflow read the sms which we got?

I see app is up and running with out waiting for OTP

**Comment by sidpagariya** [comment]
Hi, so generally IFTTT takes up to 10 seconds to detect there is a new SMS that matches that search. You might want to double check if IFTTT has been given proper permissions because that seemed to be a problem on my phone when I was testing it on my Android phone. It'll be even better if you disable battery optimization for IFTTT and allow full background usage which will make the process flawless.

I would also double-check on the ngrok side if you put the right URL from ngrok into the applet when creating it on IFTTT. If you don't see requests being logged in the terminal window with ngrok, then IFTTT is not sending requests correctly. But if you do see requests on ngrok but this program is not detecting the OTP properly, then it's likely a bug on my side, with the program itself.

If you could please double-check, that would be awesome! I'll leave this open until you follow-up, thanks!

**Comment by ghost** [comment]
My doubt, app should request for new OTP and wait for it right? I see its not like. its simple starting with out OTP

**Comment by sidpagariya** [comment]
So on startup the program will make you enter the OTP once manually, and every 5 minutes after that it will try to request a new OTP and hopefully will get notified by IFTTT of the new SMS, parse it, and continue normally.

**Comment by ghost** [comment]
no, its not asking for OTP when start. it keep on looking for slots.. and not getting OTP on phone also

**Comment by ghost** [comment]
I can see automatedOtp is default false. so its going for getAndVerifyOTP function

**Comment by sidpagariya** [comment]
Do you mind helping me with the logs? If the OTPs are not being received on the phone either then yes it seems like there’s a problem with the program. Please make sure you’ve passed in the boolean values correctly in the index.ts file, to enable the IFTTT workflow and also please double check your IFTTT applet that you made

**Comment by sidpagariya** [comment]
Yes so you need to update the flats on the last line of the index.ts file as mentioned in the README file, yep!

**Comment by ghost** [comment]
I make it true now getting below exception
Error: Cannot find module 'K:\cowincode\new\src\server.ts'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)

**Comment by sidpagariya** [comment]
Looks like you might be missing the server.ts file. You will need to make sure your repository is up to date and also please update the yarn package dependencies since those have changed as well

**Comment by ghost** [comment]
I took latest code but did not see any like server.ts in src folder ? even github also

**Comment by sidpagariya** [comment]
Oh I just checked as well, so so sorry about that, it should be good now! My most humble apologies in not pushing that up, should be good!

**Comment by sidpagariya** [comment]
If you could pull down now, it should have the `server.ts` file in there.

**Comment by ghost** [comment]
its working now. thanks

**Comment by ghost** [comment]
> Oh I just checked as well, so so sorry about that, it should be good now! My most humble apologies in not pushing that up, should be good!

hey no need sorry, you are helping so many peoples. just asking as i am new to this technology 

now app reading otp automatically

**Comment by sidpagariya** [comment]
Glad it worked out, thank you for opening an issue and helping with quick steps to reproduce the issue!
